### ISSUE TITLE
Font name confuses Windows

### ISSUE THREAD

**Issue by DLasher106** [notofonts/old-italic#3]
Some parts of Windows seem to think that the name `Noto Sans Old Italic` refers to an italic version of a font called `Noto Sans Old`. For example, the Font picker dialog shows:
![Screenshot 2024-05-12 212210](https://github.com/notofonts/old-italic/assets/18547206/de4597a3-6d93-4f4b-8958-7a54bec1611b)

I did some testing with TTX. In the OS/2 table, if the fsSelection bit 8 (WWS) is set, then Windows accepts the name `Noto Sans Old Italic` as correct:
![Screenshot 2024-05-12 212437](https://github.com/notofonts/old-italic/assets/18547206/fc10b66f-d013-4561-aaa7-c53ab19bcf0e)

**Comment by simoncozens** [comment]
Thanks for catching this and also for coming up with a fix! I'm not surprised that this font name causes problems with implementations...
